access_key_id: "$AWS_ACCESS_KEY_ID"
before_install: "docker build -t tomwic/docker-react -f Dockerfile.dev ."
deploy: 
  app: docker-react
  bucker_name: elasticbeanstalk-eu-central-1-860639283213
  bucker_path: docker-react
  env: Docker-react-env
  provider: elasticbeanstalk
  region: eu-central-1
  edge: true
language: generic
script: "docker run -e CI=true tomwic/docker-react npm run test -- --coverage"
secret_access_key: 
  secure: "$AWS_SECRET_ACCESS_KEY"
services: docker
skip_cleanup: true
sudo: required
true: 
  branch: master
