--- 
access_key_id: AKIA4QYQZJAGYY65IH5J
before_install: "docker build -t tomwic/docker-react -f Dockerfile.dev ."
deploy: 
  app: docker-react
  bucker_name: elasticbeanstalk-eu-central-1-860639283213
  bucker_path: docker-react
  env: Docker-env
  provider: elasticbeanstalk
  region: eu-central-1
detect_encoding: true
edge: true
language: generic
script: "docker run -e CI=true tomwic/docker-react npm run test"
secret_access_key: 
  secure: 3JdGTg0rMzvSIIFwuLxvhdqn8m06YWyPV7XHn6KV
services: docker
skip_cleanup: true
sudo: required
true: 
  branch: master
